openapi: 3.0.0
info:
  title: Agentary API
  version: 1.0.0
paths:
  /events:
    post:
      summary: Submit usage event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsageEvent'
      responses:
        '200':
          description: OK
components:
  schemas:
    UsageEvent:
      type: object
      properties:
        tenant_id:
          type: string
        event_type:
          type: string
        timestamp:
          type: string
          format: date-time
