name: Validate Contracts

on:
  pull_request:
    paths:
      - "schemas/**"

jobs:
  contract-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Spectral on OpenAPI
        run: npx @stoplight/spectral lint schemas/openapi/agentary-internal-v1.yaml

      - name: Run AJV schema tests
        run: node ci/scripts/run-ajv-tests.js
